<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>wgsl</string>
		</array>
		<key>name</key>
		<string>WGSL</string>
		<key>scopeName</key>
		<string>source.wgsl</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#line_comments</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#keywords</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#functions</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#function_calls</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#constants</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#types</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#variables</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#punctuation</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>line_comments</key>
			<dict>
				<key>comment</key>
				<string>single line comment</string>
				<key>name</key>
				<string>comment.line.double-slash.wgsl</string>
				<key>match</key>
				<string>\s*//.*</string>
			</dict>
			<key>functions</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>function definition</string>
						<key>name</key>
						<string>meta.function.definition.wgsl</string>
						<key>begin</key>
						<string>\b(fn)\s+([A-Za-z0-9_]+)((\()|(&lt;))</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.other.fn.wgsl</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.wgsl</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.round.wgsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\{</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.curly.wgsl</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#line_comments</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#keywords</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#function_calls</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#constants</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#types</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variables</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#punctuation</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>function_calls</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>function/method calls</string>
						<key>name</key>
						<string>meta.function.call.wgsl</string>
						<key>begin</key>
						<string>([A-Za-z0-9_]+)(\()</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.wgsl</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.round.wgsl</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\)</string>
						<key>endCaptures</key>
						<array>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.round.wgsl</string>
							</dict>
						</array>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#line_comments</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#keywords</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#function_calls</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#constants</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#types</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variables</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#punctuation</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>constants</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>decimal float literal</string>
						<key>name</key>
						<string>constant.numeric.float.wgsl</string>
						<key>match</key>
						<string>(-?\b[0-9][0-9]*\.[0-9][0-9]*)([eE][+-]?[0-9]+)?\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>int literal</string>
						<key>name</key>
						<string>constant.numeric.decimal.wgsl</string>
						<key>match</key>
						<string>-?\b0x[0-9a-fA-F]+\b|\b0\b|-?\b[1-9][0-9]*\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>uint literal</string>
						<key>name</key>
						<string>constant.numeric.decimal.wgsl</string>
						<key>match</key>
						<string>\b0x[0-9a-fA-F]+u\b|\b0u\b|\b[1-9][0-9]*u\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>boolean constant</string>
						<key>name</key>
						<string>constant.language.boolean.wgsl</string>
						<key>match</key>
						<string>\b(true|false)\b</string>
					</dict>
				</array>
			</dict>
			<key>types</key>
			<dict>
				<key>comment</key>
				<string>types</string>
				<key>name</key>
				<string>storage.type.wgsl</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>scalar Types</string>
						<key>name</key>
						<string>storage.type.wgsl</string>
						<key>match</key>
						<string>\b(bool|i32|u32|f32)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>reserved scalar Types</string>
						<key>name</key>
						<string>storage.type.wgsl</string>
						<key>match</key>
						<string>\b(i64|u64|f64)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>vector/matrix types</string>
						<key>name</key>
						<string>storage.type.wgsl</string>
						<key>match</key>
						<string>\b(vec[2-4]|mat[2-4]x[2-4])\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>atomic types</string>
						<key>name</key>
						<string>storage.type.wgsl</string>
						<key>match</key>
						<string>\b(atomic)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>array types</string>
						<key>name</key>
						<string>storage.type.wgsl</string>
						<key>match</key>
						<string>\b(array)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>Custom type</string>
						<key>name</key>
						<string>entity.name.type.wgsl</string>
						<key>match</key>
						<string>\b([A-Z][A-Za-z0-9]*)\b</string>
					</dict>
				</array>
			</dict>
			<key>variables</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>variables</string>
						<key>name</key>
						<string>variable.other.wgsl</string>
						<key>match</key>
						<string>\b(?&lt;!(?&lt;!\.)\.)(?:r#(?!(crate|[Ss]elf|super)))?[a-z0-9_]+\b</string>
					</dict>
				</array>
			</dict>
			<key>punctuation</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>comma</string>
						<key>name</key>
						<string>punctuation.comma.wgsl</string>
						<key>match</key>
						<string>,</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>curly braces</string>
						<key>name</key>
						<string>punctuation.brackets.curly.wgsl</string>
						<key>match</key>
						<string>[{}]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>parentheses, round brackets</string>
						<key>name</key>
						<string>punctuation.brackets.round.wgsl</string>
						<key>match</key>
						<string>[()]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>semicolon</string>
						<key>name</key>
						<string>punctuation.semi.wgsl</string>
						<key>match</key>
						<string>;</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>square brackets</string>
						<key>name</key>
						<string>punctuation.brackets.square.wgsl</string>
						<key>match</key>
						<string>[\[\]]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>angle brackets</string>
						<key>name</key>
						<string>punctuation.brackets.angle.wgsl</string>
						<key>match</key>
						<string>(?&lt;!=)[&lt;&gt;]</string>
					</dict>
				</array>
			</dict>
			<key>keywords</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>other keywords</string>
						<key>name</key>
						<string>keyword.control.wgsl</string>
						<key>match</key>
						<string>\b(bitcast|block|break|case|continue|continuing|default|discard|else|elseif|enable|fallthrough|for|function|if|loop|private|read|read_write|return|storage|switch|uniform|workgroup|write)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>reserved keywords</string>
						<key>name</key>
						<string>keyword.control.wgsl</string>
						<key>match</key>
						<string>\b(asm|const|do|enum|handle|mat|premerge|regardless|typedef|unless|using|vec|void|while)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>storage keywords</string>
						<key>name</key>
						<string>keyword.other.wgsl storage.type.wgsl</string>
						<key>match</key>
						<string>\b(let|var)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>type keyword</string>
						<key>name</key>
						<string>keyword.declaration.type.wgsl storage.type.wgsl</string>
						<key>match</key>
						<string>\b(type)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>enum keyword</string>
						<key>name</key>
						<string>keyword.declaration.enum.wgsl storage.type.wgsl</string>
						<key>match</key>
						<string>\b(enum)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>struct keyword</string>
						<key>name</key>
						<string>keyword.declaration.struct.wgsl storage.type.wgsl</string>
						<key>match</key>
						<string>\b(struct)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>fn</string>
						<key>name</key>
						<string>keyword.other.fn.wgsl</string>
						<key>match</key>
						<string>\bfn\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>logical operators</string>
						<key>name</key>
						<string>keyword.operator.logical.wgsl</string>
						<key>match</key>
						<string>(\^|\||\|\||&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>logical AND, borrow references</string>
						<key>name</key>
						<string>keyword.operator.borrow.and.wgsl</string>
						<key>match</key>
						<string>&amp;(?![&amp;=])</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>assignment operators</string>
						<key>name</key>
						<string>keyword.operator.assignment.wgsl</string>
						<key>match</key>
						<string>(\+=|-=|\*=|/=|%=|\^=|&amp;=|\|=|&lt;&lt;=|&gt;&gt;=)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>single equal</string>
						<key>name</key>
						<string>keyword.operator.assignment.equal.wgsl</string>
						<key>match</key>
						<string>(?&lt;![&lt;&gt;])=(?!=|&gt;)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>comparison operators</string>
						<key>name</key>
						<string>keyword.operator.comparison.wgsl</string>
						<key>match</key>
						<string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>math operators</string>
						<key>name</key>
						<string>keyword.operator.math.wgsl</string>
						<key>match</key>
						<string>(([+%]|(\*(?!\w)))(?!=))|(-(?!&gt;))|(/(?!/))</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>dot access</string>
						<key>name</key>
						<string>keyword.operator.access.dot.wgsl</string>
						<key>match</key>
						<string>\.(?!\.)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>dashrocket, skinny arrow</string>
						<key>name</key>
						<string>keyword.operator.arrow.skinny.wgsl</string>
						<key>match</key>
						<string>-&gt;</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>
